[build]
  command = "pnpm build"
  publish = ".next"
  [build.environment]
    NODE_VERSION = "20.17.0"
    NEXT_BUILD_CONCURRENCY = "1"
    NODE_ENV = "production"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# 确保静态资源不被重定向
[[redirects]]
  from = "/_next/static/*"
  to = "/.next/static/:splat"
  status = 200

# API 路由重定向配置
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# 健康检查路由
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

# SPA 回退规则，确保客户端导航正常
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"

# Headers 配置
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "production"

[context.branch-deploy.environment]
  NODE_ENV = "production"
